# Generated by Django 3.2.7 on 2021-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211022_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='adress',
            field=models.TextField(default='tehran'),
        ),
    ]
